//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20DTH1A_LT_WEB_BaiThuHoach_ThaiThanhDat_2000004681.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string tenSP { get; set; }
        public string hinhDD { get; set; }
        public string ndTomTat { get; set; }
        public int maLoai { get; set; }
        public string noiDung { get; set; }
        public string taiKhoan { get; set; }
        public string dvt { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public Nullable<int> giaBan { get; set; }
        public Nullable<int> giamGia { get; set; }
        public string nhaSanXuat { get; set; }
    
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
